#include "export/PLYExporter.hpp"
#include "utils/Logger.hpp"
#include <iomanip>
#include <chrono>

namespace kf {

std::string PLYExporter::generate_header(size_t vertex_count, size_t face_count) {
    std::stringstream ss;
    ss << "ply\n";
    ss << "format ascii 1.0\n";
    ss << "comment Generated by KinectFusionQt\n";
    ss << "comment Timestamp: "
       << std::chrono::system_clock::now().time_since_epoch().count() << "\n";
    ss << "element vertex " << vertex_count << "\n";
    ss << "property float x\n";
    ss << "property float y\n";
    ss << "property float z\n";
    ss << "property float nx\n";
    ss << "property float ny\n";
    ss << "property float nz\n";
    ss << "property uchar red\n";
    ss << "property uchar green\n";
    ss << "property uchar blue\n";
    ss << "element face " << face_count << "\n";
    ss << "property list uchar uint vertex_indices\n";
    ss << "end_header\n";
    return ss.str();
}

std::string PLYExporter::generate_ply_data(const Mesh& mesh) {
    std::stringstream ss;
    ss << std::fixed << std::setprecision(6);

    // Vertices
    for (size_t i = 0; i < mesh.positions.size(); ++i) {
        const auto& pos = mesh.positions[i];
        const auto& nrm = mesh.normals[i];
        uint8_t r = 128, g = 128, b = 128;
        if (i * 3 + 2 < mesh.colors.size()) {
            r = mesh.colors[i * 3];
            g = mesh.colors[i * 3 + 1];
            b = mesh.colors[i * 3 + 2];
        }

        ss << pos.x() << " " << pos.y() << " " << pos.z() << " " << nrm.x()
           << " " << nrm.y() << " " << nrm.z() << " " << static_cast<int>(r)
           << " " << static_cast<int>(g) << " " << static_cast<int>(b) << "\n";
    }

    // Faces (triangles)
    for (size_t i = 0; i < mesh.indices.size(); i += 3) {
        ss << "3 " << mesh.indices[i] << " " << mesh.indices[i + 1] << " "
           << mesh.indices[i + 2] << "\n";
    }

    return ss.str();
}

ExportResult PLYExporter::export_mesh(const Mesh& mesh,
                                     const std::string& output_path) {
    ExportResult result;

    if (mesh.is_empty()) {
        result.success = false;
        result.error_message = "Mesh is empty";
        KF_LOG_ERROR("PLY export: ", result.error_message);
        return result;
    }

    auto start_time = std::chrono::high_resolution_clock::now();

    KF_LOG_INFO("Exporting PLY: ", mesh.vertex_count(), " vertices, ",
               mesh.triangle_count(), " triangles");

    // Generate header
    std::string header =
        generate_header(mesh.positions.size(), mesh.triangle_count());

    // Generate data
    std::string data = generate_ply_data(mesh);

    // Combine
    std::string full_ply = header + data;

    // Write
    result.success = write_file(output_path, full_ply.data(), full_ply.size());

    if (result.success) {
        result.output_path = output_path;
        result.file_size_bytes = full_ply.size();

        auto end_time = std::chrono::high_resolution_clock::now();
        result.processing_time_ms =
            std::chrono::duration<float, std::milli>(end_time - start_time)
                .count();

        KF_LOG_INFO("PLY export successful: ", result.file_size_bytes,
                   " bytes");
    } else {
        result.error_message = "File write failed";
    }

    return result;
}

}  // namespace kf
