// This file is autogenerated. Changes will be overwritten.
#include "BMPI5EA7AM/moc_ControlPanel.cpp"
#include "BMPI5EA7AM/moc_MainWindow.cpp"
#include "BMPI5EA7AM/moc_MetricsPanel.cpp"
#include "BMPI5EA7AM/moc_NavigationGizmo.cpp"
#include "BMPI5EA7AM/moc_OpenGLWidget.cpp"
